In [1]:
import pandas as pd

In [2]:
from supabase import create_client, Client
from dotenv import load_dotenv
import os

In [3]:
load_dotenv()

url = os.getenv("supabase_url")
key = os.getenv("supabase_key")

supabase: Client = create_client(url,key)

In [ ]:
try:
    despesas = supabase.table("tb_despesas").select("*").execute()
except Exception as e:
    print(e)

In [5]:
despesas = pd.DataFrame(despesas.data)

In [107]:
#display(despesas)

In [92]:
ano = ['2026', '2027', '2028', '2029', '2030']

In [41]:
mes = [
    'Janeiro',
    'Fevereiro', 
    'Março', 
    'Abril',
    'Maio', 
    'Junho', 
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro'
    ]

In [94]:
cartoes = [
    'Nubank',
    'Mercado Pago',
    'Santander',
    'XP',
]

In [95]:
cadastro_despesa = {
    'Descriçao': ['Macbook'],
    'Balanço': ['05/2026'],
    'Categoria': ['Parcelado'],
    'Data despesa': ['2026-05-30'],
    'Cartão': ['Nubank'],
    'Local': [''],
    'Responsável': [''],
    'Valor': [5437,22],
    'Qtd. Parcelas': [24]
}

In [96]:
despesa = {
    'descricao': [],
    'balanco': [],
    'categoria': [],
    'data_despesa': [],
    'cartao': [],
    'local': [],
    'responsavel': [],
    'valor': [],
    'parcela': []
}

In [97]:
data = cadastro_despesa['Data despesa'][0]
mes = int(data[5:7])
ano = int(data[0:4])

valor = cadastro_despesa['Valor'][0]
int_qtd_parcelas = int(cadastro_despesa['Qtd. Parcelas'][0])
valor_parcelado = valor/int_qtd_parcelas

for i in range(cadastro_despesa['Qtd. Parcelas'][0]):

    parcela = i + 1

    if mes == 13:
        mes = 1 
        ano += 1

    despesa['descricao'].append(cadastro_despesa['Descriçao'][0])

    if mes < 10:
        despesa['balanco'].append(f'0{mes}/{ano}')
    else:
        despesa['balanco'].append(f'{mes}/{ano}')

    despesa['categoria'].append(cadastro_despesa['Categoria'][0])
    despesa['data_despesa'].append(cadastro_despesa['Data despesa'][0])
    despesa['cartao'].append(cadastro_despesa['Cartão'][0])
    despesa['local'].append(cadastro_despesa['Local'][0])
    despesa['responsavel'].append(cadastro_despesa['Responsável'][0])
    despesa['valor'].append(f'{valor_parcelado: .2f}')
    despesa['parcela'].append(f'{parcela}/{cadastro_despesa['Qtd. Parcelas'][0]}')

    mes += 1

In [106]:
df_despesa = pd.DataFrame(despesa)

#display(df_despesa)

# Inserir Registro

In [ ]:
#lista_para_envio = df_despesa.to_dict('records')

#supabase.table("despesas").insert(lista_para_envio).execute()

In [8]:
display(despesas)

,id,descricao,balanco,categoria,data_despesa,cartao,local,responsavel,valor,parcela
0,1,Açaí Ifood,08/2026,Alimentação,2026-06-28,Mercado Pago,NaN,NaN,33.73,NaN
1,2,Macbook,05/2026,Parcelado,2026-05-30,Nubank,,,226.54,1/24
2,3,Macbook,06/2026,Parcelado,2026-05-30,Nubank,,,226.54,2/24
3,4,Macbook,07/2026,Parcelado,2026-05-30,Nubank,,,226.54,3/24
4,5,Macbook,08/2026,Parcelado,2026-05-30,Nubank,,,226.54,4/24
...,...,...,...,...,...,...,...,...,...,...
56,57,Teste Celular 2,07/2026,Parcelado,2026-07-05,XP,,,60.00,1/1
57,58,Teste apos alterar nome projeto,07/2026,Alimentação,2026-07-05,Nubank,,,3.79,1/1
58,59,teste apos reestruturacao,07/2026,Plano,2026-07-05,Nubank,,,5.00,1/2
59,60,teste apos reestruturacao,08/2026,Plano,2026-07-05,Nubank,,,5.00,2/2
60,61,Ajuste funcao cadastro,08/2026,Alimentação,2026-08-12,Nubank,,,2.00,1/1

In [16]:
df_mes_atual = despesas[despesas["balanco"] == "07/2026"]

In [17]:
df_despesa_por_categoria = df_mes_atual[["categoria","valor"]].groupby("categoria").sum()
display(df_despesa_por_categoria)

              valor
categoria
Alimentação  445.79
Outros         3.40
Parcelado    574.94
Plano          5.00

In [19]:
df_despesa_por_cartao = df_mes_atual[["cartao","valor"]].groupby("cartao").sum()
display(df_despesa_por_cartao)

               valor
cartao
Mercado Pago   78.40
Nubank        830.73
XP            120.00

In [57]:
ano = "2026"

In [58]:
df_ano = despesas[despesas["balanco"].str.contains(ano)]

In [59]:
df_despesa_total_por_ano = df_ano[["balanco","valor"]].groupby("balanco").sum().reset_index()

datas = pd.to_datetime(df_despesa_total_por_ano["balanco"], format="%m/%Y")

df_despesa_total_por_ano["balanco"] = datas.dt.strftime("%B")

display(df_despesa_total_por_ano)

     balanco    valor
0        May   226.54
1       June   226.54
2       July  1029.13
3     August   442.27
4  September   226.54
5    October   226.54
6   November   226.54
7   December   226.54

In [60]:
mapa_meses = {
    "01": "Janeiro", "02": "Fevereiro", "03": "Março", "04": "Abril",
    "05": "Maio", "06": "Junho", "07": "Julho", "08": "Agosto",
    "09": "Setembro", "10": "Outubro", "11": "Novembro", "12": "Dezembro"
}

df_despesa_total_por_ano = df_ano[["balanco", "valor"]].groupby("balanco").sum().reset_index()

df_despesa_total_por_ano["balanco"] = df_despesa_total_por_ano["balanco"].str[:2].map(mapa_meses)

display(df_despesa_total_por_ano)

    balanco    valor
0      Maio   226.54
1     Junho   226.54
2     Julho  1029.13
3    Agosto   442.27
4  Setembro   226.54
5   Outubro   226.54
6  Novembro   226.54
7  Dezembro   226.54